security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        database_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            provider: database_provider
            jwt: ~
        api_login:
            pattern: ^/api/token
            stateless: true
            json_login:
                check_path: /api/token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|api)/
            security: false

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

    access_control:
        - { path: ^/api/token, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: ROLE_USER }
        - { path: ^/api/account, roles: ROLE_USER }
        - { path: ^/api/contact, roles: ROLE_USER }
        - { path: ^/api/users, roles: ROLE_USER }
        - { path: ^/api/devis, roles: ROLE_USER }
        - { path: ^/api/users/change_password, roles: ROLE_USER }
        - { path: ^/api/users/delete_account, roles: ROLE_USER }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/admin/contact, roles: ROLE_ADMIN }
        - { path: ^/api/, roles: ROLE_USER }