version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony

  web:
    image: nginx:latest
    container_name: symfony_web
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - symfony
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony

  adminer:
    image: adminer
    container_name: symfony_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data: