version: '3.8'

services:
  db:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_DB: TGP_site
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - tgp_data:/var/lib/postgresql/data

volumes:
  tgp_data: